# Generated by Django 5.1 on 2024-09-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marlin_app', '0002_invoice_itemtag_order_orderitem_store_storeitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentcard',
            name='card_number',
            field=models.IntegerField(),
        ),
    ]
