# Generated by Django 5.1 on 2024-09-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marlin_app', '0003_alter_userpaymentcard_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='picture',
            field=models.ImageField(upload_to='store_pictures/'),
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_type',
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='picture',
            field=models.ImageField(upload_to='product_pictures/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(upload_to='user_pictures/'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.ManyToManyField(to='marlin_app.storetype'),
        ),
    ]
